### ISSUE TITLE
main.py rprof -sX:Y:Z does not work

### ISSUE THREAD

**Issue by labrosse** [mulvrova/StagPy#8]
It used to work but does not any more. Only works without the Z arg, ie for every step. Apparently an array size problem.

Traceback (most recent call last):
  File "/home/stephane/bin/stagpy", line 81, in <module>
    main_func()
  File "/home/stephane/bin/stagpy", line 78, in main_func
    args.func(args)
  File "/home/stephane/Python/StagPy/commands.py", line 20, in rprof_cmd
    rprof.rprof_cmd(args)
  File "/home/stephane/Python/StagPy/rprof.py", line 402, in rprof_cmd
    plotprofiles(['Temperature'], 1)
  File "/home/stephane/Python/StagPy/rprof.py", line 375, in plotprofiles
    axax[1].semilogy(tsteps[0:ilast, 2], tempdif/tempdif[0])
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1613, in semilogy
    l = self.plot(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1373, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 304, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 282, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 223, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension

**Comment by labrosse** [comment]
Solved
